<a href="https://colab.research.google.com/github/honghaerim/AI-programming/blob/main/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D_4%EC%A3%BC%EC%B0%A8%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x = np.array(range(24)).reshape(2,4,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [21]:
import numpy as np
lotto = []
for _ in range(3):
  a = np.arange(1, 46)
  np.random.shuffle(a)
  lotto.append(a[:6])

lotto = np.array(lotto)

print('lotto \n', lotto)

lotto 
 [[24  8  1 40 35 34]
 [30  5 26 34 39 45]
 [30 26 29 22 18 28]]


In [20]:
import numpy as np

shape = (3, 3, 6)
array = np.random.randint(0, 20, shape)
print('3차원배열 \n', array)

3차원배열 
 [[[ 6 18  9  7  7 16]
  [13  3 16 14  1  0]
  [ 2 17 14  6  2  8]]

 [[ 0  1  5 11  8 18]
  [17 16  8  4 17  3]
  [13  2  6 17  1 10]]

 [[ 3  9  2  2 17 16]
  [19  0  2 16 13  8]
  [11  3 17 13 10  7]]]


In [22]:
import numpy as np

shape = (5, 6)

array = np.random.randint(0, 100, shape)

print('2차원배열 \n', array)

2차원배열 
 [[44 29 54 55 66 74]
 [46 96 35  2  7 35]
 [11 49 88 58 67 60]
 [37 75  4 39 74  4]
 [72 19 68 56 55 76]]


In [27]:
import numpy as np

temp = np.arange(48)

np.random.shuffle(temp)

array = temp.reshape((4, 3, 4))

print("3차원배열 \n", array)

3차원배열 
 [[[41 20 46  8]
  [24 22 31 40]
  [36  3 47 32]]

 [[ 7 12 38 23]
  [14 13  2  4]
  [ 9 19 42 33]]

 [[27 21 18 30]
  [39  0 15 37]
  [17 25 43 34]]

 [[28 11  5 16]
  [ 6 45 26 29]
  [ 1 10 44 35]]]


In [29]:
import numpy as np

temp = np.arange(48)

np.random.shuffle(temp)

array = temp.reshape((6, 8))

print("2차원배열 \n", array)

2차원배열 
 [[12 25 37 14 16 15 31 35]
 [43  9 39 34 27 47 26  7]
 [ 0 36  2  1 30 45 22 23]
 [20 33 17 32 18  6 41 29]
 [42 21 38 10  3 44 40  8]
 [28 46  5 11 24  4 13 19]]
